In [1]:

from Experiment import Experiment
import matplotlib.pyplot as plt
import Plotters 
import plotly.graph_objects as go
import plotly
import numpy as np

import time
import matplotlib.cm as colormap

%matplotlib qt


loadir = 'J:/My Drive/dark 2022/csv_dark' # dir to save the data frame in # H:\My Drive\Ronis Exp\sagiv\data_analysis
exp_name =['manipulated_2022_02_03_dark','manipulated_2023_08_10_100ms','manipulated_2023_08_09_80ms','manipulated_2023_08_09_60ms','manipulated_2023_08_06_40ms',]

# ['manipulated_2023_08_07_10ms',
#             'manipulated_2023_08_06_40ms',
#            'manipulated_2023_08_09_60ms',
#            'manipulated_2023_08_09_80ms',
#            'manipulated_2023_08_10_100ms',
#            'manipulated_2022_02_03_dark',
#            'manipulated_2022_01_31_darkdown']

def dont_show_movs(exp_name,movs_to_del):
    return [mov_name for mov_name in experiments[exp_name].mov_names if mov_name not in movs_to_del ] 

mov_dark_delete = ['mov30','mov40','mov57','mov59']
mov_100_delete = ['mov10','mov102','mov19','mov34','mov35','mov47','mov51','mov52','mov66','mov68','mov73','mov90']
mov_80_delete = ['mov119','mov49','mov97','mov99']
mov_40_delete = ['mov64']
mov_60_delete = ['mov12','mov13','mov147','mov165','mov21','mov24','mov26','mov48','mov86']
mov_10_delete = ['mov46','mov54']
mov_5_delete = ['mov44']


color_map = colormap.datad["tab10"]['listed']

experiments = {exp:Experiment(loadir,exp) for exp in exp_name} # load experiments


In [2]:
# calculations - projections, frequency, angles

[exp.from_vector_to_wing_body('Y_x_body',['vectors','body'])  for exp in experiments.values()] # smooth and derive


[exp.smooth_prop_movies('CM_real_x_body',['','_dot','_dot_dot'],'body')  for exp in experiments.values()] # smooth and derive


[exp.project_axes_movies(['X_x_body_projected','X_y_body_projected'], add_to_vectors = ['vectors','body'])  for exp in experiments.values()] # X_body axis projected to xy plane
[exp.project_axes_movies(['Y_x_body_projected','Y_y_body_projected'],axis = 'Y_x_body',add_to_vectors = ['vectors','body'])  for exp in experiments.values()] # X_body axis projected to xy plane

[exp.project_axes_movies(['CM_dot_xax','CM_dot_yax'],axis = 'CM_real_x_body_dot_smth',wing_body = 'body',add_to_vectors = ['body','vectors'])  for exp in experiments.values()] # Velocity direction in the projected X_body axes (xy plane) 

# calculate the size of the velocity projected on the xy plane
[exp.project_prop_movies('CM_real_x_body_dot_smth',header_name = 'CM_dot_x',three_col = 2,ax_to_proj = 'X_x_body_projected',add_to_vectors = True)  for exp in experiments.values()]
[exp.project_prop_movies('CM_real_x_body_dot_smth',header_name = 'CM_dot_y',three_col = 2,ax_to_proj = 'Y_x_body_projected',add_to_vectors = True)  for exp in experiments.values()]


# calculate the size of the acceleration projected on the xy plane
[exp.project_prop_movies('CM_real_x_body_dot_dot_smth',header_name = 'CM_dot_dot_x',three_col = 2,ax_to_proj = 'X_x_body_projected')  for exp in experiments.values()]
[exp.project_prop_movies('CM_real_x_body_dot_dot_smth',header_name = 'CM_dot_dot_y',three_col = 2,ax_to_proj = 'Y_x_body_projected')  for exp in experiments.values()]

[exp.pqr_movies() for exp in experiments.values()] # calculate p,q,r (angular velocity in body axis)

[exp.mean_mean_props_movies('phi_rw','phi_lw','mean_wing','mean_mean_phi') for exp in experiments.values()] # calculate the mean value of two properties


[exp.substruct_first_frame('yaw_body','body')  for exp in experiments.values()] # substract the zero frame from a property ( {prop}_min_ref_frame )

# calculate the difference between current direction and another one at the same time:
# the angle between Xbody on the xy plane and the velocity direction on the xy plane 
[exp.delta_ang_all_time_movies('X_x_body_projected','CM_dot_xax','slip_angle_beta',three_col = 2) for exp in experiments.values()] 

# calculate the difference in angle between current property and in referance frame:
# the angle between Xbody on the xy (in 0 time) plane and Xbody on xy plane 
[exp.delta_ref_ang_movies('X_x_body_projected','delta_ang_Xax',axis = 'X_x_body_projected')  for exp in experiments.values()]

# the angle between Xbody on the xy (in 0 time) plane and the velocity direction on the xy plane 
[exp.delta_ref_ang_movies('CM_dot_xax','delta_ang_CM_dot_x',axis = 'CM_dot_xax',delta_ang = 0) for exp in experiments.values()]




# project velocity and accelerations
[exp.project_prop_all_axes_movies('CM_real_x_body_dot_smth',header_name = 'CM_dot_x',three_col = 2,ax_to_proj = 'X_x_body_projected')  for exp in experiments.values()]
[exp.project_prop_all_axes_movies('CM_real_x_body_dot_smth',header_name = 'CM_dot_y',three_col = 2,ax_to_proj = 'Y_x_body_projected')  for exp in experiments.values()]

[exp.project_prop_all_axes_movies('CM_real_x_body_dot_dot_smth',header_name = 'CM_dot_dot_y',three_col = 2,ax_to_proj = 'Y_x_body_projected')  for exp in experiments.values()]
[exp.project_prop_all_axes_movies('CM_real_x_body_dot_dot_smth',header_name = 'CM_dot_dot_x',three_col = 2,ax_to_proj = 'X_x_body_projected')  for exp in experiments.values()]

[exp.project_prop_all_axes_movies('CM_real_x_body_dot_dot_smth',header_name = 'CM_dot_dot_y_body',three_col = 2,ax_to_proj = 'Y_x_body')  for exp in experiments.values()]

# calculate amplitude of phi and frequency
[exp.calculate_phi_amp_movies('rw','mean_body')  for exp in experiments.values()]
[exp.calculate_phi_amp_movies('lw','mean_body')  for exp in experiments.values()]

[exp.calculate_freq_movies('phi_rw_min_idx', 'mean_body')  for exp in experiments.values()]
[exp.calculate_freq_movies('phi_lw_min_idx', 'mean_body')  for exp in experiments.values()]


# averge properties by stroke 
props_to_mean = ['x','y','z']
[[exp.mean_by_stroke_movies(f'CM_real_{x}_body_dot_dot_smth','mean_body','body')  for exp in experiments.values()] for x in props_to_mean]
[[exp.mean_by_stroke_movies(f'CM_dot_dot_{x}_projected_all_axes','mean_body','body')  for exp in experiments.values()] for x in ['x','y']]
[[exp.mean_by_stroke_movies(f'CM_dot_x_projected','mean_body','body')  for exp in experiments.values()] for x in props_to_mean]

[[exp.mean_by_stroke_movies(f'X_{x}_body_projected','mean_body','body')  for exp in experiments.values()] for x in ['x','y']]
[[exp.mean_by_stroke_movies(f'Y_{x}_body_projected','mean_body','body')  for exp in experiments.values()] for x in ['x','y']]




# histogram calculations
exp = experiments[list(experiments.keys())[0]]
[exp.get_peaks_movies('q','max') for exp in experiments.values()]
[exp.get_peaks_movies('CM_dot_dot_x_projected','min') for exp in experiments.values()]
[exp.get_peaks_movies('pitch_y_frame','max') for exp in experiments.values()]
[exp.get_peaks_movies('pitch_body','max') for exp in experiments.values()]
[exp.get_peaks_movies('CM_dot_x_projected','min') for exp in experiments.values()]
[exp.get_peaks_movies('CM_dot_x_projected','zero_v') for exp in experiments.values()]
[exp.get_peaks_movies('delta_ang_Xax','max') for exp in experiments.values()]
[exp.get_peaks_movies('CM_dot_dot_x_projected','peaks_max',t0 = 5, t1 = 100) for exp in experiments.values()]
[exp.get_peaks_movies('CM_dot_x_projected','half_v') for exp in experiments.values()]

[exp.subtract_interest_time_from_time('CM_dot_x_projected_zero_v','time_m_zero_v') for exp in experiments.values()]



[[exp.norm_prop_movies(f'CM_real_{ax}_body_dot_smth',f'vel_norm')  for exp in experiments.values()] for ax in ['x']]
[[exp.norm_prop_movies(f'CM_real_{ax}_body_dot_dot_smth',f'acc_norm')  for exp in experiments.values()] for ax in ['x']]


c:\Users\Roni\Documents\experiment-analysis\data_analysis\Movie.py:161: RuntimeWarning:

invalid value encountered in arccos

c:\Users\Roni\Documents\experiment-analysis\data_analysis\Movie.py:414: RuntimeWarning:

divide by zero encountered in divide



[[None, None, None, None, None]]

In [3]:

# the angle between Xbody on the xy (in 0 time) plane and the velocity direction on the xy plane 
[exp.delta_ref_ang_movies('CM_dot_x_projected','delta_ang_proj_v',axis = 'CM_dot_x_projected',delta_ang = 0) for exp in experiments.values()]


[None, None, None, None, None]

In [4]:

for exp in list(experiments.values())[3:4]:
    for mov_name in exp.mov_names:
        mov = exp.get_mov(mov_name)

        vel = mov.get_prop('CM_dot_xax',wing_body = 'body',three_col=3)

        plt.plot(np.arccos(np.dot(vel,vel[mov.ref_frame]))*180/np.pi)




C:\Users\Roni\AppData\Local\Temp\ipykernel_17948\765714221.py:7: RuntimeWarning:

invalid value encountered in arccos



In [414]:
vel[mov.ref_frame]

array([0.79586304, 0.60547669, 0.08623291])

In [424]:
np.dot(vel,vel[mov.ref_frame])

array([1.00477955, 1.00482682, 1.00487353, ..., 0.13096026, 0.1304617 ,
       0.12996145])

In [376]:
# mean of velocity norm
acc_norm = []
for exp in list(experiments.values()):
    for mov_name in exp.mov_names:
        mov = exp.get_mov(mov_name)
        acc_norm.append(mov.get_prop('acc_norm',wing_body='body')[mov.ref_frame])



# acceleration - response time
np.mean(acc_norm)
th = np.mean(acc_norm) + np.std(acc_norm)*2
tim = []
acc =[]

t0 = 15
for exp in list(experiments.values()):
    for mov_name in exp.mov_names:
        mov = exp.get_mov(mov_name)
        idx_t0, idx_t1 = mov.t0_t1_idx(t0, t1)
        acc_to_th = mov.get_prop('acc_norm',wing_body='body')[idx_t0:]
        time_cut = mov.get_prop('time',wing_body='body')[idx_t0:]


        if acc_to_th[mov.ref_frame] < 1.7:

            acc.append(acc_to_th[acc_to_th > th])
            tim.append(time_cut[acc_to_th > th])


min_time = [t[0] for t in tim if (len(t) > 0) and (t[0] < 120) ]
min_acc = [ac[0] for ac in acc if len(ac) > 0 ]
plt.figure(),plt.hist(min_time, bins = 20)
plt.axvline(np.mean(min_time), color='k', linestyle='dashed', linewidth=1)
plt.title('response tims [ms]')
plt.xlabel('time [ms]')


Text(0.5, 0, 'time [ms]')

In [292]:

fig = go.Figure()
prop = 'vel_norm'
[exp.plot_prop_movies(prop,'body',fig,case = 'plot_exp',prop_x = 'time',color = color_map[idx],legend = exp.pertubation_name) for idx,exp in enumerate(experiments.values())]
fig.show()


fig = go.Figure()
prop = 'acc_norm'
[exp.plot_prop_movies(prop,'body',fig,case = 'plot_exp',prop_x = 'time',color = color_map[idx],legend = exp.pertubation_name) for idx,exp in enumerate(experiments.values())]
fig.show()



In [434]:
fig = go.Figure()
prop = 'delta_ang_proj_v'
[exp.plot_prop_movies(prop,'body',fig,case = 'plot_exp',prop_x = 'time',color = color_map[idx],legend = exp.pertubation_name) for idx,exp in enumerate(experiments.values())]
fig.show()

In [393]:

fig = go.Figure()
prop = 'slip_angle_beta'
[exp.plot_prop_movies(prop,'body',fig,case = 'plot_exp',prop_x = 'time',color = color_map[idx],legend = exp.pertubation_name) for idx,exp in enumerate(experiments.values())]
fig.show()

fig = go.Figure()
prop = 'delta_ang_Xax'
[exp.plot_prop_movies(prop,'body',fig,case = 'plot_exp',prop_x = 'time',color = color_map[idx],legend = exp.pertubation_name) for idx,exp in enumerate(experiments.values())]
fig.show()



In [169]:
degree_to_rotate = mov.get_prop('pitch_body',wing_body='body',three_col=3)*np.pi/180
degree_to_rotate[:,0] = degree_to_rotate[:,0] - 45*np.pi/180
plt.plot(degree_to_rotate[:,0]*180/np.pi)

In [178]:
exp

'manipulated_2022_02_03_dark'

In [8]:
exp = experiments['manipulated_2023_08_09_60ms']
# mov = exp.get_mov('mov11')

def rotation_matrix(yaw,pitch,roll):
    roll_mat = np.vstack([[1,0,0],[0 ,np.cos(roll),-np.sin(roll)],[0, np.sin(roll), np.cos(roll)]])
    pitch_mat = np.vstack([[np.cos(pitch),0,np.sin(pitch)],[0, 1,0],[-np.sin(pitch), 0, np.cos(pitch)]])
    yaw_mat = np.vstack([[np.cos(yaw),-np.sin(yaw),0],[np.sin(yaw),np.cos(yaw),0],[0, 0, 1]])

    return yaw_mat @ pitch_mat @ roll_mat


rotate_to_strk = True

t1 = 120

fig = go.Figure()


# fig = Plotters.scatter_3d(fig,cm_zero,rotated_cm[:,0], mov.name)
angle_z = []
angle_x = []

zh = []
for t0 in [50,60,70,80,90,100]:
    data = []

    for exp in experiments.values():
        for mov_name in exp.mov_names:
            mov = exp.get_mov(mov_name)

            idx_t0,idx_t1 = mov.t0_t1_idx(t0,t1)
            degree_to_rotate = mov.get_prop('pitch_body',wing_body='body',three_col=3)*np.pi/180
            degree_to_rotate[:,0] = degree_to_rotate[:,0] 

            
            rot_mat = mov.rotation_matrix(degree_to_rotate[idx_t0,1],-degree_to_rotate[idx_t0,0],degree_to_rotate[idx_t0,2])
            acc = mov.get_prop('CM_real_x_body_dot_dot_smth',wing_body='body',three_col=3)

            # acc_rotated = np.matmul(acc,rot_mat)
            acc_rotated = np.dot(rot_mat.T,acc.T).T
            acc_rotated = np.dot(mov.rot_mat_sp.T,acc_rotated.T).T

            data.append(acc_rotated[idx_t0,:]/np.linalg.norm(acc_rotated[idx_t0,:]))
            # plt.scatter(idx_t0,acc[idx_t0][0])
        
    data = np.vstack(data)
    angle_z.append(np.arcsin(data[:,2])*180/np.pi)
    angle_x.append(np.arccos(-data[:,0])*180/np.pi)

    zh.append(data[:,2])

    fig.add_trace(go.Scatter3d(
    x=data[:,0],
    y=data[:,1],
    z=data[:,2],
    name = mov_name,
    mode= 'markers',
    marker=dict(size=3),))


fig.add_trace(go.Scatter3d(
x=[0],
y=[0],
z=[0],
name = mov_name,
marker=dict(size=15),))

fig.update_layout(
    title=f'time [ms] - {t0}')

fig.show()



In [9]:
plt.plot([np.std(angle_z[k]) for k in range(len(angle))])

NameError: name 'angle' is not defined

In [11]:
plt.figure()
[plt.hist(angle_z[k],alpha = 0.8,bins = 30) for k in [4]]

[(array([ 1.,  0.,  1.,  0.,  1.,  1.,  0.,  0.,  1.,  4.,  1.,  1.,  3.,
          2.,  5., 11., 20., 15., 15., 26., 34., 23., 22., 14.,  9.,  1.,
          1.,  0.,  0.,  1.]),
  array([-81.44659831, -76.51221892, -71.57783953, -66.64346014,
         -61.70908075, -56.77470136, -51.84032198, -46.90594259,
         -41.9715632 , -37.03718381, -32.10280442, -27.16842503,
         -22.23404564, -17.29966626, -12.36528687,  -7.43090748,
          -2.49652809,   2.4378513 ,   7.37223069,  12.30661008,
          17.24098947,  22.17536885,  27.10974824,  32.04412763,
          36.97850702,  41.91288641,  46.8472658 ,  51.78164519,
          56.71602457,  61.65040396,  66.58478335]),
  <BarContainer object of 30 artists>)]

In [150]:
plt.plot(acc)
plt.scatter(idx_t0,acc[idx_t0][0])

In [188]:
len(experiments['manipulated_2023_08_09_80ms'].mov_names)

21

In [155]:
np.vstack(data)

array([[ 0.1547613 , -0.37149178,  0.91544677],
       [ 0.55292973, -0.18285108,  0.81291709],
       [ 0.44934544, -0.88090007, -0.14867327],
       [ 0.95672385,  0.18053692, -0.22822333],
       [-0.69950861,  0.28413852, -0.65570802],
       [ 0.96717264,  0.00546164,  0.25406151],
       [ 0.20393565, -0.94728878, -0.24709153],
       [-0.1736371 , -0.21502376, -0.96104888],
       [ 0.01955168,  0.68151148,  0.7315462 ],
       [-0.4667207 ,  0.1355304 , -0.87395841],
       [ 0.65523674,  0.75109002, -0.08079978],
       [ 0.4118894 ,  0.11931584, -0.90338854],
       [-0.652332  , -0.15663318,  0.74157198],
       [ 0.19099918,  0.87390952,  0.44699158],
       [-0.33640153, -0.81993929,  0.46317769],
       [-0.68961777, -0.45228821, -0.56556406],
       [ 0.45612778,  0.47866778,  0.75021637],
       [ 0.10326599,  0.61743517, -0.77981405],
       [-0.35623851, -0.42581669, -0.83172969],
       [-0.06920237, -0.93913018,  0.33651973],
       [ 0.11912989,  0.58192095, -0.804

In [382]:
# exp_list = []
# for exp in experiments.values():
#     prop = 'time'
#     time_list = [exp.get_mov(mov).get_prop(prop,wing_body='body') for mov in exp.mov_names]

#     prop = 'pitch_body'
#     prop_list = [exp.get_mov(mov).get_prop(prop,wing_body='body') for mov in exp.mov_names]

#     time_min_max = [np.min(np.vstack(time_list)),np.max(np.vstack(time_list))]

#     mean_prop = []
#     for t in np.arange(time_min_max[0],time_min_max[1],1/16):
#         j = 0 
#         for idx,tm in enumerate(time_list):
#             j = 0
#             prop_mean = 0
#             if t in tm: 
#                 prop_mean += (prop_list[idx][t==tm])
#                 j += 1
#         if j > 0:
#             mean_prop.append(prop_mean/j)
#         else:
#             mean_prop.append(np.nan)
#     plt.plot(np.arange(time_min_max[0],time_min_max[1],1/16),mean_prop,label = exp.experiment_name)
# plt.legend()




# mean_prop

c:\Users\Roni\anaconda3\envs\deep_hull\lib\site-packages\numpy\core\shape_base.py:65: VisibleDeprecationWarning:

Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.



[nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 array([48.29646157]),
 array([48.27519039]),
 array([48.25386534]),
 array([48.23248862]),
 array([48.21106245]),
 array([48.18958904]),
 array([48.16807061]),
 array([48.14650937]),
 array([48.12490754]),
 array([48.10

In [195]:
fig = go.Figure()
prop = 'acc_norm_x'
[exp.plot_prop_movies(prop,'body',fig,case = 'plot_exp',prop_x = 'time',color = color_map[idx],legend = exp.pertubation_name) for idx,exp in enumerate(experiments.values())]
fig.show()

In [13]:
# cm rotated by yaw/velocity in ref frame

[exp.rotate_prop_movies('CM_real_x_body',['rotated_cm_x','rotated_cm_y','rotated_cm_z'],rotate_by_yaw = False) for exp in experiments.values()]

[None, None, None, None, None]

In [383]:
[exp.angles_between_vector_and_ref_frame_movies('CM_real_x_body_dot_smth',['delta_velocity']) for exp in experiments.values()]

c:\Users\Roni\Documents\experiment-analysis\data_analysis\Movie.py:82: RuntimeWarning:

invalid value encountered in arccos



[None, None, None, None, None]

In [384]:
perc_stoped = []
legend = []
for idx,exp in enumerate(experiments.values()):
    didnt_stop = sum(np.isnan(exp.interest_points['CM_dot_x_projected_zero_v']))[0]
    num_of_exp = len(exp.mov_names)

    plt.plot(idx,(num_of_exp - didnt_stop)/num_of_exp*100,'*',label = exp.experiment_name)
plt.legend()


In [386]:
# הפרש בין מהירות זד בזמן כלשהו ביחס למהירות זד בזמן 0 
t0 = 0
t1 = 80
hist_plus = []
hist_minus = []


plt.figure()
for mov_name in exp.mov_names:
    mov = exp.get_mov(mov_name)
    cm_z_dot = mov.get_prop('CM_real_z_body_dot_smth','body')

    time_lst = mov.t0_t1_idx(t0,t1)
    if cm_z_dot[mov.ref_frame]> 0: 
        hist_plus.append(cm_z_dot[time_lst[1]] - cm_z_dot[mov.ref_frame])
    else: 
        hist_minus.append(cm_z_dot[time_lst[1]] - cm_z_dot[mov.ref_frame])
    
plt.hist([np.hstack(hist_plus),np.hstack(hist_minus)],stacked = True,alpha = 0.5)

plt.show()



In [9]:
exp = experiments['manipulated_2022_01_31_darkdown']
fig = go.Figure()
exp.plot_prop_movies('CM_real_z_body_dot_smth','body',fig,case = 'plot_mov',prop_x = 'time' )
fig.show()

In [10]:
exp = experiments['manipulated_2022_01_31_darkdown']
fig = go.Figure()
exp.plot_prop_movies('delta_velocity','body',fig,case = 'plot_mov',prop_x = 'time' )
fig.show()

fig = go.Figure()
exp = experiments['manipulated_2022_02_03_dark']
exp.plot_prop_movies('delta_velocity','body',fig,case = 'plot_mov',prop_x = 'time' )
fig.show()

KeyError: 'manipulated_2022_02_03_dark'

In [11]:
exp = experiments['manipulated_2022_01_31_darkdown']
mov = ['mov101']

exp.plot_3d_traj_movies('CM_dot_x_projected',mov = mov)
fig.show()


In [15]:
exp = experiments['manipulated_2022_02_03_dark']


fig = go.Figure()
fr = -1
skip = 100

# fig = Plotters.scatter_3d(fig,cm_zero,rotated_cm[:,0], mov.name)
for mov_name in exp.mov_names:
    mov = exp.get_mov(mov_name)
    data = mov.get_prop('rotated_cm_x','body',three_col=3)*1000
    
    fig.add_trace(go.Scatter3d(
    x=data[0:fr:skip,0],
    y=data[0:fr:skip,1],
    z=data[0:fr:skip,2],
    name = mov_name,
    marker=dict(size=3),
    ))

  
fig.add_trace(go.Scatter3d(
x=[data[mov.ref_frame,0]],
y=[data[mov.ref_frame,1]],
z=[data[mov.ref_frame,2]],
name = mov_name,
marker=dict(size=15),))
fig.show()

In [379]:
exp = experiments['manipulated_2023_08_09_60ms']
delta_velocity = []
delta_v =[]
delta_ang = 70
for mov_name in exp.mov_names:
    mov = exp.get_mov(mov_name)
    delta_velocity = mov.get_prop('delta_ang_CM_dot_x',wing_body='body')
    time_prop = mov.get_prop('time',wing_body='body')

    if 200 < max(time_prop):
        t0 = 200
        t1 = -1
        time_lst = mov.t0_t1_idx(t0,t1)


        delta_v.append(delta_velocity[time_lst[0],:])
delta_v = np.array(delta_v)
delta_v[delta_v > 360] = 360 - delta_v[delta_v > 360]
delta_v[delta_v < 360] = 360 - delta_v[delta_v < 360]

print(np.sum((np.abs(delta_v) < delta_ang) | ( np.abs(360-delta_v) < delta_ang) | ( np.abs(-360+delta_v) < delta_ang)))
len(exp.mov_names)



41


83

In [79]:
plt.plot(delta_v)

PLOTS

In [52]:
fig = go.Figure()
exp = experiments['manipulated_2023_08_09_60ms']
exp.plot_prop_movies('delta_ang_CM_dot_x','body',fig,case = 'plot_mov' ,add_horizontal_line=None)
fig.show()

In [32]:
# plot pitch and roll vs acceleration
fig = go.Figure()
exp = experiments['manipulated_2022_02_03_dark']
exp.plot_prop_movies('pitch_body','body',fig,case = 'plot_mov',prop_x = 'CM_dot_dot_x_projected_all_axes' ,add_horizontal_line=None,name = 'calculated')
fig.show()

fig = go.Figure()
exp.plot_prop_movies('roll_body','body',fig,case = 'plot_mov',prop_x = 'CM_dot_dot_y_projected_all_axes' ,add_horizontal_line=None,name = 'calculated')
fig.show()

In [44]:
# plot slip angle and delta yaw

exp = experiments['manipulated_2022_02_03_dark']
fig = go.Figure()
exp.plot_prop_movies('slip_angle_beta','body',fig,case = 'plot_mov',prop_x = 'time' ,add_horizontal_line=None)
fig.show()

fig = go.Figure()
exp.plot_prop_movies('delta_ang_Xax','body',fig,case = 'plot_mov',prop_x = 'time' ,add_horizontal_line=None)
fig.show()

In [33]:
# plot body angles
exp = experiments['manipulated_2023_08_09_60ms']
fig = go.Figure()
exp.plot_prop_movies('roll_body','body',fig,case = 'plot_mov',prop_x = 'time' ,add_horizontal_line=None)
fig.show()

fig = go.Figure()
exp.plot_prop_movies('pitch_body','body',fig,case = 'plot_mov',prop_x = 'time' ,add_horizontal_line=None)
fig.show()

fig = go.Figure()
exp.plot_prop_movies('yaw_body','body',fig,case = 'plot_mov',prop_x = 'time' ,add_horizontal_line=None)
fig.show()


In [107]:
# velocity and acceleration
exp = experiments['manipulated_2022_01_31_darkdown']
fig = go.Figure()
exp.plot_prop_movies('CM_dot_x_projected','body',fig,case = 'plot_mov',prop_x = 'time' ,add_horizontal_line=None)
fig.show()

fig = go.Figure()
exp.plot_prop_movies('CM_dot_dot_x_projected','body',fig,case = 'plot_mov',prop_x = 'time' ,add_horizontal_line=None)
fig.show()


fig = go.Figure()
exp.plot_prop_movies('CM_real_z_body_dot_smth','body',fig,case = 'plot_mov',prop_x = 'time' ,add_horizontal_line=None)
fig.show()

In [49]:
exp = experiments['manipulated_2023_08_09_60ms']
fig = go.Figure()
exp.plot_prop_movies('CM_real_z_body_dot_smth','body',fig,case = 'plot_mov',prop_x = 'time' ,add_horizontal_line=None)
fig.show()

In [19]:
# plot wings angle
exp = experiments['manipulated_2023_08_09_60ms']

phi_r_color = [[256,0,0]]*len(exp.mov_names)
phi_l_color = [[0,0,256]]*len(exp.mov_names)

fig = go.Figure()
exp.plot_prop_movies('theta_rw','wing',fig,case = 'plot_mov',prop_x = 'time',color = phi_r_color )
exp.plot_prop_movies('theta_lw','wing',fig,case = 'plot_mov',prop_x = 'time', color = phi_l_color)
fig.show()

fig = go.Figure()
exp.plot_prop_movies('psi_rw','wing',fig,case = 'plot_mov',prop_x = 'time',color = phi_r_color )
exp.plot_prop_movies('psi_lw','wing',fig,case = 'plot_mov',prop_x = 'time', color = phi_l_color)
fig.show()


fig = go.Figure()
exp.plot_prop_movies('phi_lw','wing',fig,case = 'plot_mov',prop_x = 'time',color = phi_l_color )
exp.plot_prop_movies('phi_rw','wing',fig,case = 'plot_mov',prop_x = 'time', color = phi_r_color)

fig.show()



In [36]:
exp = experiments['manipulated_2023_08_09_60ms']
mov = ['mov101']
exp.plot_3d_traj_movies('CM_dot_x_projected',mov = mov)
fig.show()



In [37]:
time_vec = [10,60,100,220,280]

xbins = dict(start=0,end=360,size = 10)
fig = Plotters.subplot_histograms_delta_prop(time_vec,experiments,'delta_ang_CM_dot_x',color_map,xbins,'body')
fig.show()


In [57]:

t_vec = [0,20,75,150,200]
delta_t = 73*5/16000*1000
prop = 'freq_phi_rw_min_idx'
data = [exp.mean_prop_time_vector_movies(prop,delta_t,t_vec, mov = False) for exp in  experiments.values()]


fig = go.Figure()
[Plotters.vplot(dat,fig,'t0','freq_phi_rw_min_idx',exp_name) for dat,exp_name in zip(data,experiments.keys())]
fig.show()


prop = 'CM_dot_x_projected'
data = [exp.mean_prop_time_vector_movies(prop,delta_t,t_vec, mov = False,sub_mean = False) for exp in  experiments.values()]


fig = go.Figure()
[Plotters.vplot(dat,fig,'t0','CM_dot_x_projected',exp_name) for dat,exp_name in zip(data,experiments.keys())]
fig.show()

plotly.offline.plot(fig, filename=f'I:/My Drive/Research/Dark/article/figures/html/CM_dot_x_violin_plot.html',auto_open=False)



c:\Users\Roni\Documents\experiment-analysis\data_analysis\Movie.py:372: RuntimeWarning:

Mean of empty slice

c:\Users\Roni\Documents\experiment-analysis\data_analysis\Movie.py:372: RuntimeWarning:

Mean of empty slice

c:\Users\Roni\Documents\experiment-analysis\data_analysis\Movie.py:372: RuntimeWarning:

Mean of empty slice

c:\Users\Roni\Documents\experiment-analysis\data_analysis\Movie.py:372: RuntimeWarning:

Mean of empty slice



'I:/My Drive/Research/Dark/article/figures/html/CM_dot_x_violin_plot.html'

In [58]:

point_name = 'CM_dot_x_projected_zero_v'
list_trace,layout = zip(*[exp.interest_point_hist(point_name,xbins = dict(start=0,end=300, size=5)) for exp in experiments.values()])

fig = go.Figure(data=list_trace, layout=layout[0]).show()


point_name = 'CM_dot_dot_x_projected_min'
list_trace,layout = zip(*[exp.interest_point_hist(point_name,xbins = dict(start=0,end=300, size=5)) for exp in experiments.values()])
fig = go.Figure(data=list_trace, layout=layout[0]).show()


point_name = 'CM_dot_dot_x_projected_peaks_max'
list_trace,layout = zip(*[exp.interest_point_hist(point_name,xbins = dict(start=0,end=300, size=5)) for exp in experiments.values()])
fig = go.Figure(data=list_trace, layout=layout[0]).show()
